### ISSUE TITLE
F´ New Fails on PIP Installs

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime-tools#34]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

To reproduce (user was using a virtual environment):  

1. Install from pip without source. `pip install fprime-tools`
2. Run new component: `fprime-util new --component`

Error:

```
fprime-util new –component
[WARNING] **** fprime-util new is prototype functionality ****
[INFO] Cookiecutter source: using builtin

Traceback (most recent call last):
  File ".../bin/fprime-util", line 8, in <module>
    sys.exit(main())
  File ".../lib/python3.8/site-packages/fprime/util/__main__.py", line 14, in main
    return fprime.util.build_helper.utility_entry(args=sys.argv[1:])
  File ".../lib/python3.8/site-packages/fprime/util/build_helper.py", line 155, in utility_entry
    runners[parsed.command](build, parsed, cmake_args, make_args)
  File ".../lib/python3.8/site-packages/fprime/util/cli.py", line 112, in template
    return new_component(build.deployment, parsed.platform, parsed.verbose, build)
  File ".../lib/python3.8/site-packages/fprime/fbuild/interaction.py", line 265, in new_component
    cookiecutter(source, extra_context={"component_namespace": deployment.name})
  File ".../lib/python3.8/site-packages/cookiecutter/main.py", line 67, in cookiecutter
    repo_dir, cleanup = determine_repo_dir(
  File ".../lib/python3.8/site-packages/cookiecutter/repository.py", line 131, in determine_repo_dir
    raise RepositoryNotFound(
cookiecutter.exceptions.RepositoryNotFound: A valid repository for ".../lib/python3.8/site-packages/fprime/fbuild/../cookiecutter_templates/cookiecutter-fprime-component" could not be found in the following locations:
.../lib/python3.8/site-packages/fprime/fbuild/../cookiecutter_templates/cookiecutter-fprime-component
```

**Comment by LeStarch** [comment]
Note: likely the template files are not included in the package generation.

Workaround: install from source with `pip install -e <path to fprime-tools clone>`
